{
   "technology":{
      "name":"Coldfusion",
      "type":"Server Side Programming"
   },
   "versions":[
      {
         "name":"Allaire Cold Fusion 1.0",
         "releaseDate":"01/01/1995",
         "releaseYear":"1995",
		 "features":[""],
		 "references":"",
         "changes":{
            "storageLocationCode":null,
            "storageState":"",
            "storageCountry":"NL",
            "storageZipcode":"",
            "storageEmail":"eew@dkkdk.com",
            "storagePhone":"+31.765.242.650"
         }
      },
      {
         "name":"Allaire Cold Fusion 1.5",
         "releaseDate":"01/01/1996",
         "releaseYear":"1996",
		 "features":[""],
		 "references":"",
         "changes":{
            "storageLocationCode":null,
            "storageState":"",
            "storageCountry":"NL",
            "storageZipcode":"",
            "storageEmail":"eew@dkkdk.com",
            "storagePhone":"+31.765.242.650"
         }
      },
      {
         "name":"Allaire Cold Fusion 2",
         "releaseDate":"01/11/1996",
         "releaseYear":"1996",
		 "features":[""],
		 "references":"",
         "changes":{
            "storageLocationCode":null,
            "storageState":"",
            "storageCountry":"NL",
            "storageZipcode":"",
            "storageEmail":"eew@dkkdk.com",
            "storagePhone":"+31.765.242.650"
         }
      },
      {
         "name":"Allaire Cold Fusion 3",
         "releaseDate":"01/06/1997",
         "releaseYear":"1997",
		 "features":[""],
		 "references":"",
         "changes":{
            "storageLocationCode":null,
            "storageState":"",
            "storageCountry":"NL",
            "storageZipcode":"",
            "storageEmail":"eew@dkkdk.com",
            "storagePhone":"+31.765.242.650"
         }
      },
      {
         "name":"Allaire ColdFusion 4.0",
         "releaseDate":"01/11/1998",
         "releaseYear":"1998",
		 "features":[""],
		 "references":"",
         "changes":{
            "storageLocationCode":null,
            "storageState":"",
            "storageCountry":"NL",
            "storageZipcode":"",
            "storageEmail":"eew@dkkdk.com",
            "storagePhone":"+31.765.242.650"
         }
      },
      {
         "name":"Allaire ColdFusion 4.5",
         "releaseDate":"01/11/1999",
         "releaseYear":"1999",
		 "features":[""],
		 "references":"",
         "changes":{
            "storageLocationCode":null,
            "storageState":"",
            "storageCountry":"NL",
            "storageZipcode":"",
            "storageEmail":"eew@dkkdk.com",
            "storagePhone":"+31.765.242.650"
         }
      },
      {
         "name":"Macromedia ColdFusion 5",
         "releaseDate":"01/06/2001",
         "releaseYear":"2011",
		 "features":[""],
		 "references":"",
         "changes":{
            "storageLocationCode":null,
            "storageState":"",
            "storageCountry":"NL",
            "storageZipcode":"",
            "storageEmail":"eew@dkkdk.com",
            "storagePhone":"+31.765.242.650"
         }
      },
      {
         "name":"Macromedia ColdFusion 6",
         "releaseDate":"01/06/2002",
         "releaseYear":"2002",
		 "features":[""],
		 "references":"",
         "changes":{
            "storageLocationCode":null,
            "storageState":"",
            "storageCountry":"NL",
            "storageZipcode":"",
            "storageEmail":"eew@dkkdk.com",
            "storagePhone":"+31.765.242.650"
         }
      },
      {
         "name":"Macromedia ColdFusion 7",
         "releaseDate":"01/02/2005",
         "releaseYear":"2005",
		 "features":[""],
		 "references":"",
         "changes":{
            "storageLocationCode":null,
            "storageState":"",
            "storageCountry":"NL",
            "storageZipcode":"",
            "storageEmail":"eew@dkkdk.com",
            "storagePhone":"+31.765.242.650"
         }
      },
      {
         "name":"Adobe ColdFusion 8",
         "releaseDate":"01/07/2007",
         "releaseYear":"2007",
		 "features":[""],
		 "references":"",
         "changes":{
            "storageLocationCode":null,
            "storageState":"",
            "storageCountry":"NL",
            "storageZipcode":"",
            "storageEmail":"eew@dkkdk.com",
            "storagePhone":"+31.765.242.650"
         }
      },
      {
         "name":"Adobe ColdFusion 9",
         "releaseDate":"01/09/2009",
         "releaseYear":"2009",
		 "features":[""],
		 "references":"",
         "changes":{
            "storageLocationCode":null,
            "storageState":"",
            "storageCountry":"NL",
            "storageZipcode":"",
            "storageEmail":"eew@dkkdk.com",
            "storagePhone":"+31.765.242.650"
         }
      },
      {
         "name":"Adobe ColdFusion 10",
         "releaseDate":"01/06/2012",
         "releaseYear":"2012",
		 "features":[""],
		 "references":"",
         "changes":{
            "storageLocationCode":null,
            "storageState":"",
            "storageCountry":"NL",
            "storageZipcode":"",
            "storageEmail":"eew@dkkdk.com",
            "storagePhone":"+31.765.242.650"
         }
      },
      {
         "name":"Adobe ColdFusion 11",
         "releaseDate":"01/04/2014",
         "releaseYear":"2014",
		 "features":[""],
		 "references":"",
         "changes":{
            "storageLocationCode":null,
            "storageState":"",
            "storageCountry":"NL",
            "storageZipcode":"",
            "storageEmail":"eew@dkkdk.com",
            "storagePhone":"+31.765.242.650"
         }
      },
      {
         "name":"Adobe ColdFusion 2016",
         "releaseDate":"01/02/2016",
         "releaseYear":"2016",
		 "features":[""],
		 "references":"",
         "changes":{
            "storageLocationCode":null,
            "storageState":"",
            "storageCountry":"NL",
            "storageZipcode":"",
            "storageEmail":"eew@dkkdk.com",
            "storagePhone":"+31.765.242.650"
         }
      }
   ]
}
